/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pitcherproblem;

import apcscvm.CVMProgram;
import apcscvm.ViewCanvas;

/**
 *
 * @author DSTIGANT
 */
public class PitcherProblemGUI extends javax.swing.JFrame
{
    private PitcherProblemModel model;
    private PitcherProblemDisplay view;
    
    /**
     * Creates new form PitcherProblemGUI
     */
    public PitcherProblemGUI( boolean player)
    {
        model = new PitcherProblemModel( 8, 3, 3, 3 );
        if ( player )
        {
            view = new PitcherProblemPlayerControl();
        }
        else
        {
            view = new PitcherProblemSolverDisplay();
        }
        initComponents();
        
        new CVMProgram( (ViewCanvas)viewCanvas, view, view, model ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbPitcher1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbPitcher2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbPitcher3 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbGoal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        viewCanvas = new ViewCanvas<PitcherProblemDisplay, PitcherProblemModel>( view, model );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbPitcher1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "9", "10", "11", "12", "13" }));
        cbPitcher1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbPitcher1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pitcher 1:");

        cbPitcher2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "6", "7", "8" }));
        cbPitcher2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbPitcher2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pitcher 2:");

        cbPitcher3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "6", "7", "8" }));
        cbPitcher3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbPitcher3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Pitcher 3:");

        cbGoal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbGoal.setSelectedItem(3);
        cbGoal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbGoalActionPerformed(evt);
            }
        });

        jLabel4.setText("Goal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPitcher1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPitcher2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPitcher3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPitcher1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbPitcher2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbPitcher3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPitcher2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbPitcher2ActionPerformed
    {//GEN-HEADEREND:event_cbPitcher2ActionPerformed
        resetModel();
    }//GEN-LAST:event_cbPitcher2ActionPerformed

    private void cbPitcher1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbPitcher1ActionPerformed
    {//GEN-HEADEREND:event_cbPitcher1ActionPerformed
        resetModel();
    }//GEN-LAST:event_cbPitcher1ActionPerformed

    private void cbPitcher3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbPitcher3ActionPerformed
    {//GEN-HEADEREND:event_cbPitcher3ActionPerformed
        // TODO add your handling code here:
        resetModel();
    }//GEN-LAST:event_cbPitcher3ActionPerformed

    private void cbGoalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbGoalActionPerformed
    {//GEN-HEADEREND:event_cbGoalActionPerformed
        // TODO add your handling code here:
        resetModel();
    }//GEN-LAST:event_cbGoalActionPerformed

    private void resetModel()
    {
        int p1 = Integer.parseInt( (String)cbPitcher1.getSelectedItem() );
        int p2 = Integer.parseInt( (String)cbPitcher2.getSelectedItem() );
        int p3 = Integer.parseInt( (String)cbPitcher3.getSelectedItem() );
        int g = Integer.parseInt( (String)cbGoal.getSelectedItem() );
        
        model.reset( new PitcherConfiguration( p1, p2, p3 ), g);
        
        view.reset();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PitcherProblemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PitcherProblemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PitcherProblemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PitcherProblemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PitcherProblemGUI( true ).setVisible(true);
                new PitcherProblemGUI( false ).setVisible( true );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbGoal;
    private javax.swing.JComboBox cbPitcher1;
    private javax.swing.JComboBox cbPitcher2;
    private javax.swing.JComboBox cbPitcher3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private java.awt.Canvas viewCanvas;
    // End of variables declaration//GEN-END:variables
}
